project:
  type: website

website:
  title: "Pisaster"
  favicon: assets/images/pisaster-favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    title: false
    pinned: true
    search: false
    collapse-below: md
    logo: assets/images/pisaster-logo.png 
    right:
    - href: "mailto:hello@pisaster.com?subject=Website%20inquiry"
      text: "hello@pisaster.com"
      icon: envelope
    
    left:
    - href: index.qmd
      text: "Home"
    - href: services.qmd
      text: "Services"
    - href: about.qmd
      text: "About"

  page-footer:
    left: "&#169; 2026 Pisaster"
    border: false

format:
  html:
    theme: 
      - flatly
      - assets/scss/styles.scss
    toc: false
    fontawesome: true

editor: source
mainfont: "Lexend"

execute:
  freeze: auto
